import type { MappingEditorLabels } from './types.ts';

export const defaultLabels: MappingEditorLabels = {
	field: 'Value',
	array: 'List',
	object: 'Object',
	conditional: 'Conditional',
	concat: 'Compose List',
	tuple: 'Fixed List',
	addItem: 'Add Item',
	addSchemaField: '+ Add field…',
	newField: 'New Field',
	selectPlaceholder: '— select —',
	advanced: 'Other…',
	jsExpression: 'JS expression…',
	useSuggestions: 'Use suggestions',
	useSchemaFields: 'Use schema fields',
	customSuffix: 'custom',
	currentFields: 'All nested fields',
	currentValue: 'Current value',
	enumValues: 'Enum values',
	nestedFields: 'Nested fields',
	parentFields: 'Outer fields',
	internalVariables: 'Internal variables',
	forEach: 'forEach',
	from: 'from',
	when: 'when',
	then: 'then',
	else: 'else',
	concatItem: 'item',
	addElse: 'Add Else',
	keyPlaceholder: 'key',
	expressionPlaceholder: 'js expression',
	removeField: 'Remove field',
	moveUp: 'Move up',
	moveDown: 'Move down',
	moveUpSymbol: '↑',
	moveDownSymbol: '↓',
	removeSymbol: '×',
	useSuggestionsSymbol: '↩',
	reorder: 'Reorder',
	mappingType: 'Mapping type',
	required: 'required'
};
